<a href="https://colab.research.google.com/github/MichalMiszcz/ai_playing_music/blob/main/LSTM_autoenkoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteki

In [1]:
import torch
import torch.nn as nn

# Generowanie przykładowych danych

In [24]:
import random

random_notes = random.choices(range(1, 9), k=10)
random_times = random.choices(range(1000, 10000), k=10)

sequences = []

for n in range(512):
  lstm_sequence = [[n, dt] for n in random_notes for dt in random_times]
  sequences.append(lstm_sequence)


# Architektura sieci

In [ ]:
class AutoenkoderLSTM(nn.Module):
    def __init__(self, hidden_dim=64, input_dim=2, output_dim=2, rnn_layers=2, max_seq_len=100) -> None:
        super(AutoenkoderLSTM, self).__init__()
        self.max_seq_len = max_seq_len
        self.encoder = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, num_layers=rnn_layers, dropout=0.33, batch_first=True)
        self.decoder = nn.LSTM(input_size=hidden_dim, hidden_size=hidden_dim, num_layers=rnn_layers, dropout=0.33, batch_first=True)
        self.linear = nn.Linear(hidden_dim, output_dim)
        self.proj_h = nn.Linear(hidden_dim, hidden_dim * rnn_layers)
        self.proj_c = nn.Linear(hidden_dim, hidden_dim * rnn_layers)
        self.output_dim = output_dim

    def forward(self, x):
        batch_size = x.size(0)

        features, _ = self.encoder(x)

        input_seq = torch.cat([torch.zeros(batch_size, 1, self.output_dim).to(x.device), target[:, :-1, :]], dim=1)
        h0 = self.proj_h(features).view(batch_size, self.rnn.num_layers, -1).transpose(0, 1).contiguous()
        c0 = self.proj_c(features).view(batch_size, self.rnn.num_layers, -1).transpose(0, 1).contiguous()

        output, _ = self.decoder(input_seq, (h0, c0))

        self.linear.flatten_parameters()



# Zmienne

In [ ]:
batch_size = 8

# Uczenie

In [60]:
proj_h = nn.Linear(2, 16)
x = [[0.1, 0.2]]
x = torch.tensor(x)
print(x)
proj_1 = proj_h(x)
# view_1 = x.view(2, 2, -1).transpose(0, 1).contiguous()
proj = proj_h(x).view(2, 2, -1).transpose(0, 1).contiguous()

print(proj_1)
print(proj)

tensor([[0.1000, 0.2000]])
tensor([[-0.0599, -0.3562,  0.1286,  0.4143,  0.0901,  0.5203,  0.4646,  0.0214,
         -0.0503, -0.3505, -0.3407, -0.0952, -0.4608,  0.2438,  0.1360,  0.5337]],
       grad_fn=<AddmmBackward0>)
tensor([[[-0.0599, -0.3562,  0.1286,  0.4143],
         [-0.0503, -0.3505, -0.3407, -0.0952]],

        [[ 0.0901,  0.5203,  0.4646,  0.0214],
         [-0.4608,  0.2438,  0.1360,  0.5337]]], grad_fn=<CloneBackward0>)
